In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0, 100, (10, 2))

In [4]:
data

array([[16,  8],
       [27, 73],
       [34,  6],
       [91, 26],
       [ 7, 15],
       [59, 49],
       [48, 27],
       [64, 67],
       [65, 59],
       [43, 23]])

In [5]:
scalar_model = MinMaxScaler()

In [6]:
scalar_model.fit(data)

/Users/pool/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [7]:
scalar_model.transform(data)

array([[0.10714286, 0.02985075],
       [0.23809524, 1.        ],
       [0.32142857, 0.        ],
       [1.        , 0.29850746],
       [0.        , 0.13432836],
       [0.61904762, 0.64179104],
       [0.48809524, 0.31343284],
       [0.67857143, 0.91044776],
       [0.69047619, 0.79104478],
       [0.42857143, 0.25373134]])

In [8]:
data

array([[16,  8],
       [27, 73],
       [34,  6],
       [91, 26],
       [ 7, 15],
       [59, 49],
       [48, 27],
       [64, 67],
       [65, 59],
       [43, 23]])

In [9]:
result = scalar_model.fit_transform(data)

/Users/pool/anaconda3/envs/tensorflow/lib/python3.5/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
result

array([[0.10714286, 0.02985075],
       [0.23809524, 1.        ],
       [0.32142857, 0.        ],
       [1.        , 0.29850746],
       [0.        , 0.13432836],
       [0.61904762, 0.64179104],
       [0.48809524, 0.31343284],
       [0.67857143, 0.91044776],
       [0.69047619, 0.79104478],
       [0.42857143, 0.25373134]])

In [11]:
import pandas as pd

In [12]:
data = pd.DataFrame(data=np.random.randint(0,101, (50,4)), columns=['f1', 'f2', 'f3', 'label'])

In [13]:
data

f1  f2  f3  label
0    62  57  70     73
1    93  30  67     47
2    88  91  22     95
3    57  67  33     35
4    45  20  71     46
5    81  88   1     37
6     2  17  58     37
7     4  86  78     70
8    59   0   3     85
9    88  13  64     36
10   29  23  11      9
11   10  53  52     16
12   21  48  15     40
13   81   9  95      6
14   68  40  50      4
15   31  91   5     65
16   19  49  82     66
17   31  53  29     27
18  100  39  83     57
19   64  78  20     90
20   34  78  97     16
21   10  24  72     20
22   89  17  52     65
23   60  25  43     89
24   10  80  74      1
25   34  89  22     77
26   23  34  57     96
27   29  86  89     55
28   96  33  41     74
29   63  40  14     82
30   86  33  70     88
31   90   8  95     74
32    3  67  94     76
33    8  68  72     32
34   13  97  10      3
35   60  79  50     50
36   94  28  79     54
37   46   3  62     55
38   55  81  30     25
39   57  15  57     62
40   60  39  85     14
41   14  32  84     63
42   45  49  91     54
43   82  67  83     77
44   35   2   8      9
45   33  75  40     28
46   50   1   6     47
47   89   0  76     98
48   33  22  60     53
49   19  52  85    100

In [14]:
data.head()

f1  f2  f3  label
0  62  57  70     73
1  93  30  67     47
2  88  91  22     95
3  57  67  33     35
4  45  20  71     46

In [15]:
x = data[['f1', 'f2', 'f3']]

In [16]:
y = data['label']

In [18]:
x.head()

f1  f2  f3
0  62  57  70
1  93  30  67
2  88  91  22
3  57  67  33
4  45  20  71

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

In [22]:
X_train.shape

(35, 3)

In [24]:
X_test.shape

(15, 3)