In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.12.0


In [5]:
hello = tf.constant("hello")

In [6]:
world = tf.constant("world")

In [4]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
result = hello + world

In [8]:
hello

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [9]:
result

<tf.Tensor 'add:0' shape=() dtype=string>

In [10]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [11]:
result

b'helloworld'

## Comutations

In [12]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

In [13]:
sess

In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4,4), 10)

In [16]:
fill_mat

<tf.Tensor 'Fill:0' shape=(4, 4) dtype=int32>

In [17]:
myzeros = tf.zeros((4,4))

In [18]:
myones = tf.ones((4,4))

In [19]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [21]:
myrandn = tf.random_normal((4,4) ,mean=0, stddev=0.5)

In [24]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [25]:
my_ops = [const, myzeros, myones, myrandn, myrandu]

## interactive session

In [23]:
sess = tf.InteractiveSession()

In [30]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.38095045  0.173251   -0.14497562  0.23121385]
 [-0.13360466  0.95564544 -0.52773255  0.3062937 ]
 [-0.09670445  0.50167465  0.28791326  0.80884016]
 [-0.28959975 -0.2922858  -0.34707227 -0.6499716 ]]


[[0.13942707 0.86032057 0.7586769  0.9722687 ]
 [0.48882782 0.98641753 0.8037422  0.68439925]
 [0.88443077 0.9214475  0.95860374 0.64035535]
 [0.82994235 0.9283726  0.3604226  0.7772536 ]]




In [31]:
a = tf.constant([[1,2], [3,4]])

In [33]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [39]:
b = tf.constant([[2], [10]])

In [40]:
result = tf.matmul(a,b)

In [41]:
result.eval()

array([[22],
       [46]], dtype=int32)